/*==============================================================================
CLEANUP - Fiberific
Drops all project-specific objects. Run this to remove the demo.
==============================================================================*/

USE ROLE SYSADMIN;

DROP STREAMLIT IF EXISTS SNOWFLAKE_EXAMPLE.FIBERIFIC.FIBERIFIC_DASHBOARD;

DROP AGENT IF EXISTS SNOWFLAKE_EXAMPLE.FIBERIFIC.FIBERIFIC_AGENT;

DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_FIBERIFIC_OPS;

DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.FIBERIFIC CASCADE;

DROP WAREHOUSE IF EXISTS SFE_FIBERIFIC_WH;

DROP GIT REPOSITORY IF EXISTS SNOWFLAKE_EXAMPLE.TOOLS.SFE_FIBERIFIC_REPO;

-- PROTECTED - NEVER DROP:
-- SNOWFLAKE_EXAMPLE database
-- SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS schema
-- SNOWFLAKE_EXAMPLE.TOOLS schema
-- SFE_GIT_API_INTEGRATION
